[package]
name = "ui_layout"
version = "0.5.0"
edition = "2024"

description = "A minimal Flexbox-inspired layout engine for Rust GUI"
license = "MIT"
repository = "https://github.com/098orin/ui_layout-rs"
keywords = ["layout", "gui", "flexbox", "ui"]
categories = ["gui"]

[dependencies]
